[2025-01-24 19:33:00,213: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 19:33:00,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 19:33:00,223: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 19:33:00,224: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 29, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 15, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 11, in initiate_data_ingestion
    config=ConfigurationManager()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 11, in __init__
    self.paramss=read_yaml(params_filepath)
  File "E:\Epita\Projects\Text_summary_project\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 31, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-01-24 19:37:08,847: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 19:37:08,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 19:37:08,854: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 19:37:08,855: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 29, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 15, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 11, in initiate_data_ingestion
    config=ConfigurationManager()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 12, in __init__
    self.paramss=read_yaml(params_filepath)
  File "E:\Epita\Projects\Text_summary_project\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 31, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-01-24 19:39:02,357: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 19:39:02,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 19:39:02,365: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 19:39:02,365: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 29, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 15, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 11, in initiate_data_ingestion
    config=ConfigurationManager()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 13, in __init__
    self.paramss=read_yaml(params_filepath)
  File "E:\Epita\Projects\Text_summary_project\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\utils\common.py", line 31, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-01-24 19:39:53,941: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 19:39:53,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 19:39:53,951: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 19:39:53,983: INFO: common: created directory at: artifacts]
[2025-01-24 19:39:53,986: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 19:39:55,251: INFO: data_ingestion: File is downloaded]
[2025-01-24 19:39:55,252: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 15, in <module>
    data_ingestion_pipeline.initiate_data_ingestion()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 16, in initiate_data_ingestion
    data_ingestion.extract_zip_file()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\components\data_ingestion.py", line 31, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "E:\Epita\Projects\Text_summary_project\venv\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "E:\Epita\Projects\Text_summary_project\venv\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-01-24 19:44:25,581: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 19:44:25,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 19:44:25,615: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 19:44:25,635: INFO: common: created directory at: artifacts]
[2025-01-24 19:44:25,637: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 19:44:27,975: INFO: data_ingestion: File is downloaded]
[2025-01-24 19:44:28,334: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 20:28:57,954: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 20:28:59,814: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 20:28:59,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 20:28:59,870: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 20:28:59,882: INFO: common: created directory at: artifacts]
[2025-01-24 20:28:59,883: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 20:28:59,884: INFO: data_ingestion: File already exits]
[2025-01-24 20:29:00,444: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 20:29:00,444: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 20:29:00,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 20:29:00,452: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 20:29:00,452: INFO: common: created directory at: artifacts]
[2025-01-24 20:29:00,453: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 20:29:13,916: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 21:42:09,046: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 21:42:27,891: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 21:42:27,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:42:27,974: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:42:28,017: INFO: common: created directory at: artifacts]
[2025-01-24 21:42:28,019: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 21:42:28,052: INFO: data_ingestion: File already exits]
[2025-01-24 21:42:28,699: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 21:42:28,699: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 21:42:28,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:42:28,709: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:42:28,734: INFO: common: created directory at: artifacts]
[2025-01-24 21:42:28,735: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 21:42:36,904: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 21:42:36,905: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 21:42:37,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:42:37,071: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:42:37,073: INFO: common: created directory at: artifacts]
[2025-01-24 21:42:37,073: ERROR: main: 'ConfigurationManager' object has no attribute 'params']
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 37, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 46, in get_model_trainer_config
    params=self.params.TrainingArguments
AttributeError: 'ConfigurationManager' object has no attribute 'params'
[2025-01-24 21:47:24,836: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 21:47:28,148: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 21:47:28,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:47:28,204: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:47:28,216: INFO: common: created directory at: artifacts]
[2025-01-24 21:47:28,217: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 21:47:28,218: INFO: data_ingestion: File already exits]
[2025-01-24 21:47:28,707: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 21:47:28,707: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 21:47:28,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:47:28,717: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:47:28,718: INFO: common: created directory at: artifacts]
[2025-01-24 21:47:28,719: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 21:47:34,512: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 21:47:34,513: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 21:47:34,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:47:34,547: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:47:34,547: INFO: common: created directory at: artifacts]
[2025-01-24 21:47:34,548: INFO: common: created directory at: artifacts/model_trainer]
[2025-01-24 21:47:34,549: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 37, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 50, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
TypeError: ModelTrainerConfig() takes no arguments
[2025-01-24 21:58:16,742: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 21:58:22,251: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 21:58:22,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:58:22,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:58:22,421: INFO: common: created directory at: artifacts]
[2025-01-24 21:58:22,421: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 21:58:22,422: INFO: data_ingestion: File already exits]
[2025-01-24 21:58:23,044: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 21:58:23,045: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 21:58:23,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:58:23,055: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:58:23,055: INFO: common: created directory at: artifacts]
[2025-01-24 21:58:23,056: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 21:58:28,463: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 21:58:28,464: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 21:58:28,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 21:58:28,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 21:58:28,525: INFO: common: created directory at: artifacts]
[2025-01-24 21:58:28,617: INFO: common: created directory at: artifacts/model_trainer]
[2025-01-24 21:58:28,618: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 37, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 54, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
TypeError: ModelTrainerConfig() takes no arguments
[2025-01-24 22:07:39,578: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 22:07:41,896: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 22:07:41,920: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:07:41,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:07:41,957: INFO: common: created directory at: artifacts]
[2025-01-24 22:07:41,958: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 22:07:41,959: INFO: data_ingestion: File already exits]
[2025-01-24 22:07:42,395: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 22:07:42,395: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 22:07:42,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:07:42,404: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:07:42,405: INFO: common: created directory at: artifacts]
[2025-01-24 22:07:42,407: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 22:07:46,678: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 22:07:46,678: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 22:07:46,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:07:46,687: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:07:46,688: INFO: common: created directory at: artifacts]
[2025-01-24 22:07:46,690: INFO: common: created directory at: artifacts/model_trainer]
[2025-01-24 22:07:46,691: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 37, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 54, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
TypeError: ModelTrainerConfig() takes no arguments
[2025-01-24 22:16:03,252: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 22:16:06,024: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 22:16:06,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:16:06,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:16:06,108: INFO: common: created directory at: artifacts]
[2025-01-24 22:16:06,109: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 22:16:06,110: INFO: data_ingestion: File already exits]
[2025-01-24 22:16:06,527: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 22:16:06,527: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 22:16:06,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:16:06,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:16:06,539: INFO: common: created directory at: artifacts]
[2025-01-24 22:16:06,539: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 22:16:13,362: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 22:16:13,363: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 22:16:13,369: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:16:13,374: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:16:13,375: INFO: common: created directory at: artifacts]
[2025-01-24 22:16:13,377: INFO: common: created directory at: artifacts/model_trainer]
[2025-01-24 22:16:13,379: ERROR: main: ModelTrainerConfig() takes no arguments]
Traceback (most recent call last):
  File "E:\Epita\Projects\Text_summary_project\main.py", line 37, in <module>
    model_trainer_pipeline.initiate_model_trainer()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\pipeline\stage_3_model_trainer_pipeline.py", line 10, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "E:\Epita\Projects\Text_summary_project\src\textSummarizer\config\configuration.py", line 54, in get_model_trainer_config
    model_trainer_config=ModelTrainerConfig(
TypeError: ModelTrainerConfig() takes no arguments
[2025-01-24 22:24:48,808: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-24 22:24:51,053: INFO: main: stage Data Ingestion stage initiated]
[2025-01-24 22:24:51,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:24:51,105: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:24:51,117: INFO: common: created directory at: artifacts]
[2025-01-24 22:24:51,118: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-24 22:24:51,119: INFO: data_ingestion: File already exits]
[2025-01-24 22:24:51,540: INFO: main: Stage Data Ingestion stage Completed]
[2025-01-24 22:24:51,540: INFO: main: stage Data Transformation stage initiated]
[2025-01-24 22:24:51,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:24:51,548: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:24:51,549: INFO: common: created directory at: artifacts]
[2025-01-24 22:24:51,549: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-24 22:24:56,861: INFO: main: Stage Data Transformation stage Completed]
[2025-01-24 22:24:56,861: INFO: main: stage Model Trainer stage initiated]
[2025-01-24 22:24:56,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-24 22:24:56,869: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-24 22:24:56,870: INFO: common: created directory at: artifacts]
[2025-01-24 22:24:56,871: INFO: common: created directory at: artifacts/model_trainer]
